POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "name_mock6",
    "price": 20.25,
    "qty_stock": 4
}
###
GET http://localhost:3000/products
Content-Type: application/json

###
PUT http://localhost:3000/products/stock/cb7e6bf1-5a4f-4cfc-a4c5-2d3c11f35497
Content-Type: application/json

{
    "qty_stock": 200
}

###
PUT http://localhost:3000/products/price/cb7e6bf1-5a4f-4cfc-a4c5-2d3c11f35497
Content-Type: application/json

{
    "price": 200.45
}

###
DELETE http://localhost:3000/products/delete/cb7e6bf1-5a4f-4cfc-a4c5-2d3c11f35497
Content-Type: application/json